### ISSUE TITLE
Login tap keeps bringing error screenshot below 

### ISSUE THREAD

**Issue by SamsonAkangbe** [sosol-gmi/sosol-client#17]
![Screenshot_2021-10-19-01-14-26-687_com kiwibrowser browser](https://user-images.githubusercontent.com/39330091/137823456-e4e80802-c454-4961-9b57-f769c2aff4ca.jpg)

**Comment by h4rkl** [comment]
This should be fixed in https://github.com/sosol-gmi/sosol-client/issues/16. Cheers!
