### ISSUE TITLE
Tweet issue

### ISSUE THREAD

**Issue by Henry593** [sosol-gmi/sosol-client#18]
I used sosol site about 7 hours ago it went really smooth then I logged in later the day went to my profile and tried to view it"it says the profile does not exist

**Comment by AngryPacifist** [comment]
also on the homepage
![image_2021-10-19_101905](https://user-images.githubusercontent.com/44065385/137881107-d7b993ae-a188-489f-b39e-c3cb27649c21.png)

**Comment by h4rkl** [comment]
There were some db issues fixed in #19 which should be sorted now. Thanks for being patient :)
